### ISSUE TITLE
Heatmap (experimental)

### ISSUE THREAD

**Issue by michalk8** [theislab/interactive_plotting#29]
Add early beta version of `heatmap`

**Comment by michalk8** [comment]
Hey @Marius1311 , under `ipl.ex.heatmap`, `experimental` branch, you can find the first version of heatmap. I've started working on this 1.5 months ago but didn't finish it. 
Right now it has only these features and might be buggy (I do very little checking), but should be stable enough for you to try it out.
- box select will show the selected groups/genes in a new heatmap below (essentially better zoom in, which I might disable)
- has hover
- if `show_scatterplot=True`, when you click on a gene and have computed DPT, it will show you its expression + colored in groups (this functionality will change soon)

My plan:
- [ ] Make it work on any grid-like data (adata.X, adata.obsm, no aggregation per group)
- [x] Keep/remove the scatterplot; if keep, probably embed it in basis
- [ ] Nicer label formatting, especially for large number of genes
- [x] Dropdown for categorical kes in `adata.obs`
- [x] Add more hover annotation when aggregating (min, max, var, ...)
- [ ] Make into dotplot
- [ ] Create wrapper for gene ranks

If you have any suggestions (apart from dendrogram, which at this point I find impossible to do), they are welcome.

**Comment by Marius1311** [comment]
Hi Mike, I will certainly have a look at this and give you feedback. However, I'm currently on a trip to Boston, so might take me a week to do so.

**Comment by michalk8** [comment]
Hey, @Marius1311, once you have time, I've finished the heatmap + a very general scatterplot (both under `ipl.ex.{heatmap, scatterplot}`. I'd be glad if you could try and test them out - I've added some use cases in the notebook on `experimental` branch.

**Comment by Marius1311** [comment]
Thanks Mike, I will try to have a look later today.

**Comment by Marius1311** [comment]
I get an error when I run the last cell from the notebook,
`heatmap(adata, adata.var_names[:100], group_key='paul15_clusters')`. The traceback is

```python
['10GMP', '11DC', '12Baso', '13Baso', '14Mo', '15Mo', '16Neu', '17Neu', '18Eos', '19Lymph', '1Ery', '2Ery', '3Ery', '4Ery', '5Ery', '6Ery', '7MEP', '8Mk', '9GMP'] (10, 100)
---------------------------------------------------------------------------
DataError                                 Traceback (most recent call last)
<ipython-input-6-3be8cc3ac6db> in <module>
----> 1 heatmap(adata, adata.var_names[:100], group_key='paul15_clusters')

<ipython-input-5-a45e35d3c25a> in heatmap(adata, genes, group_key, show_scatterplot)
     51 
     52     heatmap = hv.HeatMap({'x': np.array(genes), 'y': np.array(groups), 'z': val},
---> 53                          kdims=[('x', 'Gene'), ('y', 'Group')], vdims=[('z', 'Expression')]).opts(tools=['box_select', 'hover'], xrotation=90)
     54     sel = Selection1D(source=heatmap)
     55     mean_sel = hv.DynamicMap(lambda index: heatmap_hl(heatmap, index),

~/miniconda3/envs/cellrank_new/lib/python3.6/site-packages/holoviews/element/raster.py in __init__(self, data, kdims, vdims, **params)
    939 
    940     def __init__(self, data, kdims=None, vdims=None, **params):
--> 941         super(HeatMap, self).__init__(data, kdims=kdims, vdims=vdims, **params)
    942         self.gridded = categorical_aggregate2d(self)

~/miniconda3/envs/cellrank_new/lib/python3.6/site-packages/holoviews/core/data/__init__.py in __init__(self, data, kdims, vdims, **kwargs)
    209         validate_vdims = kwargs.pop('_validate_vdims', True)
    210         initialized = Interface.initialize(type(self), data, kdims, vdims,
--> 211                                            datatype=kwargs.get('datatype'))
    212         (data, self.interface, dims, extra_kws) = initialized
    213         super(Dataset, self).__init__(data, **dict(kwargs, **dict(dims, **extra_kws)))

~/miniconda3/envs/cellrank_new/lib/python3.6/site-packages/holoviews/core/data/interface.py in initialize(cls, eltype, data, kdims, vdims, datatype)
    232                 continue
    233             try:
--> 234                 (data, dims, extra_kws) = interface.init(eltype, data, kdims, vdims)
    235                 break
    236             except DataError:

~/miniconda3/envs/cellrank_new/lib/python3.6/site-packages/holoviews/core/data/grid.py in init(cls, eltype, data, kdims, vdims)
    106                 raise error('Key dimension values and value array %s '
    107                             'shapes do not match. Expected shape %s, '
--> 108                             'actual shape: %s' % (vdim, valid_shape, shape), cls)
    109         return data, {'kdims':kdims, 'vdims':vdims}, {}
    110 

DataError: Key dimension values and value array z shapes do not match. Expected shape (19, 100), actual shape: (10, 100)

GridInterface expects gridded data, for more information on supported datatypes see http://holoviews.org/user_guide/Gridded_Datasets.html
```

**Comment by Marius1311** [comment]
Please update the notebook and include a couple of example applications for both heatmap as well as the new scatterplot so it's easy for me to see what it can do.

**Comment by michalk8** [comment]
Not sure why you got the error, do you have the last version? I though I fixed it last night. If it persists, let me know, but it work fine for me.


> Please update the notebook and include a couple of example applications for both heatmap as well as the new scatterplot so it's easy for me to see what it can do.

Donne.

**Comment by Marius1311** [comment]
will give it a go today.

**Comment by Marius1311** [comment]
I know what happened, last time I looked at the `hm.ipynb` notebook. I take it you want me to look at the `interactive_plotting_tutorial.ipynb' notebook.

**Comment by Marius1311** [comment]
Comments on the scatterplot
- legend is still a problem. It works nice as long as there is enough white space in the plot but when it gets crowded, the legend get's in the way. I would recommend two things:
  - an option 'on data', like in scanpy. 
  - an option 'outside' to have it outside the plot
- add a `layer` option - when looking at gene trends, I would often like to look at imputet data, i.e. at the `layer['Ms']`
- other than that, this is pretty awesome! I have a feeling this is getting a bit similar to what Joshua is doing, so maybe contact him to avoid too much overlap? 

Comments on heatmap
- pretty cool stuff! I like the idea of having different layers of abstraction, first looking at everything, then zooming in, and they displaying the zoomed in data in a different way!

**Comment by Marius1311** [comment]
I think someone who could give pretty good feedback on this is Malte - let me know if you want me to contact him, or whether we wait until sphinx is set up.

**Comment by michalk8** [comment]
>   * add a `layer` option - when looking at gene trends, I would often like to look at imputet data, i.e. at the `layer['Ms']`

Working on this now, since it shouldn't take me that long. After that, I will do the legend on data (shouldn't be that hard either).
In the meantime, I've added kde and marginal densities (try `kde=0` and `density='group'` or `density='all'`, the former is only for categorical obs) - I'd share with you a figure but github won't let me upload.


> I think someone who could give pretty good feedback on this is Malte - let me know if you want me to contact him, or whether we wait until sphinx is set up.

After I'm done with the `.layers` and the legend, I'd be happy for a feedback from Malte. Ultimately, I'd switch in the future to JS/Typescript + Bokeh server.

>    * pretty cool stuff! I like the idea of having different layers of abstraction, first looking at everything, then zooming in, and they displaying the zoomed in data in a different way!

I was worried it was a bit too much but I'm glad you like it.

**Comment by Marius1311** [comment]
okay, let me know once you are done with all of that and you would like me to have a look again. Can you explain a bit what you mean by switching to 'JS/Typescript + Bokeh server'? I don't really get it. At the moment, this is holoviews + bokeh, right?

**Comment by michalk8** [comment]
I've added the layers, the legend on data isn't as easy as expected - it breaks down both the datashader and decimate (the axes get squished) - therefore I haven't added them (I will fix legends in #30).

By switching I mean creating a bokeh server which could serve out these documents as separate pages - this would allow for more complex behaviour (widges, exporting of plots + data). One could also create more complex dashboards (think of cellxgene, but modular, oriented towards programmers).

Bokeh can be extended with 3rd party JS/TS libraries (I want to try it out on 3d ![scatterplot](https://github.com/bokeh/bokeh/tree/master/examples/app/surface3d) that I want to try and replicate (that and the velocityis still at the back of my mind). 

Both of these things are just for the future.

**Comment by michalk8** [comment]
Also, I've opened a pull request, if you don't find any bugs (there were several I fixed), I will then merge it.

**Comment by Marius1311** [comment]
Sure, feel free to merge. Is the new scatterplot going to replace scatter and scatterc?

**Comment by michalk8** [comment]
> Sure, feel free to merge. Is the new scatterplot going to replace scatter and scatterc?

Doing so now. No it's not to - the `scatter` and `scatterc` are still useful - e.g. multiple conditions, embeddings are percentiles.

**Comment by Marius1311** [comment]
mhm, I think we are getting too many scatter plot options.

**Comment by michalk8** [comment]
@Marius1311 
Few weeks back, I've finally added a 3D scatterplot, could you try testing it out? 
I also forgot to add dependencies (some JS library), so you will most likely get an error.
Note that the first time you run the plot it will be slower, since the TS file needs to be compiled to JS. Also it will open the plot in new windows (it's not by design, it's unfortunately necessary).
Let me know what you think.

**Comment by Marius1311** [comment]
will check it out, thanks.
